### PR TITLE
Sign up mechanism fixed

### LINKED ISSUE #479: Sign up form enables button without the password confirmation field
Sign up form for users getting enabled "too early" without the user is filling in the confirmation field.

## Expected Behavior

Sign up button only gets enabled after the user has filled in all fields.

## Current Behavior

Submit button enabled already after the user fills in the password.

### PR DESCRIPTION
**Pull request by javpet**
### What does this PR do?
- Fixing sign up only enabled after password confirmation matched
- Fixed home page button behavior

#### Description of Task to be completed?
- User can sign up as soon as they fill in all the required fields for registration, but not earlier

#### How should this be manually tested?

Forked repo methodology should work fine.

#### What are the relevant Github Issues ?

Fixes #479

### CODE REVIEW

File: cypress/integration/common/web_steps.js [hunk 1]
```diff
@@ -9,18 +9,32 @@ Given('I open Google page', () => {
   cy.visit(url)
 })
 
+/**
+ * Disable css smooth scroll, that doesn't plays nice with cypress.
+ * See https://github.com/cypress-io/cypress/issues/3200
+ */
+const disableSmoothScroll = () => {
+  cy.document().then(document => {
```
Comment (aonomike) [inline cypress/integration/common/web_steps.js:17]: thanks for this one @javpet

**Review by aonomike — APPROVED** [review]
Thanks again @javpet
